// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

class IccCameraInfo {
  IccCameraInfo({
    required this.deviceId,
    required this.name,
    required this.transportKind,
    this.model,
    this.serialNumber,
    this.isRemote = false,
  });

  /// Stable identifier — `ICDevice.persistentIDString` when available,
  /// otherwise `ICDevice.uuidString`.
  String deviceId;

  /// User-visible product name (`ICDevice.name`).
  String name;

  /// `'usb'` for USB-C wired cameras, `'network'` for shared cameras
  /// (rare on iPhone), `'unknown'` when ICA can't tell.
  String transportKind;

  String? model;

  String? serialNumber;

  bool isRemote;

  Object encode() {
    return <Object?>[
      deviceId,
      name,
      transportKind,
      model,
      serialNumber,
      isRemote,
    ];
  }

  static IccCameraInfo decode(Object result) {
    result as List<Object?>;
    return IccCameraInfo(
      deviceId: result[0]! as String,
      name: result[1]! as String,
      transportKind: result[2]! as String,
      model: result[3] as String?,
      serialNumber: result[4] as String?,
      isRemote: result[5]! as bool,
    );
  }
}

class PtpCommandResult {
  PtpCommandResult({
    required this.responseCode,
    required this.responseParams,
    this.data,
  });

  /// PTP response code (e.g. 0x2001 = OK).
  int responseCode;

  /// Response parameters (0..5 uint32 values).
  List<int> responseParams;

  /// Data-in payload, if the transaction had a data-IN phase.
  Uint8List? data;

  Object encode() {
    return <Object?>[
      responseCode,
      responseParams,
      data,
    ];
  }

  static PtpCommandResult decode(Object result) {
    result as List<Object?>;
    return PtpCommandResult(
      responseCode: result[0]! as int,
      responseParams: (result[1] as List<Object?>?)!.cast<int>(),
      data: result[2] as Uint8List?,
    );
  }
}

class PtpCommand {
  PtpCommand({
    required this.opcode,
    required this.transactionId,
    required this.params,
    this.outData,
  });

  /// PTP opcode (e.g. 0x1001 = GetDeviceInfo).
  int opcode;

  /// PTP transaction id; caller-managed.
  int transactionId;

  /// Command parameters (0..5 uint32 values).
  List<int> params;

  /// Data-OUT payload for dataOut transactions, else null.
  Uint8List? outData;

  Object encode() {
    return <Object?>[
      opcode,
      transactionId,
      params,
      outData,
    ];
  }

  static PtpCommand decode(Object result) {
    result as List<Object?>;
    return PtpCommand(
      opcode: result[0]! as int,
      transactionId: result[1]! as int,
      params: (result[2] as List<Object?>?)!.cast<int>(),
      outData: result[3] as Uint8List?,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is IccCameraInfo) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is PtpCommandResult) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is PtpCommand) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return IccCameraInfo.decode(readValue(buffer)!);
      case 130: 
        return PtpCommandResult.decode(readValue(buffer)!);
      case 131: 
        return PtpCommand.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class IccPtpHostApi {
  /// Constructor for [IccPtpHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  IccPtpHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Snapshot of currently-visible ICA camera devices.
  Future<List<IccCameraInfo>> devices() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nikon_ptp_flutter.IccPtpHostApi.devices$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<IccCameraInfo>();
    }
  }

  /// Open an ICA session on the given device. Idempotent — if a session is
  /// already open on the device, returns true immediately.
  Future<bool> openSession(String deviceId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nikon_ptp_flutter.IccPtpHostApi.openSession$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[deviceId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Send a single PTP command over the currently-open session.
  ///
  /// The native side is responsible for building the PTP command block that
  /// `ICCameraDevice.requestSendPTPCommand(_:outData:sendCommandDelegate:...)`
  /// expects. OpenSession / CloseSession opcodes are intercepted natively —
  /// they never reach ICA (the ICA session lifecycle is managed by
  /// [openSession] / [closeSession] above).
  Future<PtpCommandResult> sendCommand(PtpCommand command) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nikon_ptp_flutter.IccPtpHostApi.sendCommand$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[command]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as PtpCommandResult?)!;
    }
  }

  /// Close the ICA session on the currently-open device. No-op if none open.
  Future<void> closeSession() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nikon_ptp_flutter.IccPtpHostApi.closeSession$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class IccPtpFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// A new device appeared in the browser.
  void onDeviceAdded(IccCameraInfo device);

  /// A device disappeared (unplug / turned off).
  void onDeviceRemoved(String deviceId);

  /// Push-based PTP event from `ICCameraDeviceDelegate.didReceivePTPEvent:`.
  /// [transactionId] is the container's transaction id (usually 0 for
  /// asynchronous events unrelated to a specific request).
  void onPtpEvent(int eventCode, int transactionId, List<int> params);

  /// The active session ended for a reason other than an explicit close —
  /// device unplugged, camera powered off, or an internal ICA error.
  ///
  /// [reason] is one of: `'unplug'`, `'error'`, `'authRevoked'`, `'timeout'`.
  void onSessionEnded(String deviceId, String reason);

  /// Progress heartbeat during a pending [openSession] call.
  ///
  /// The Swift coordinator emits these at key transitions so the UI can
  /// tell "still waiting on Apple" from "media catalog is 40 % scanned"
  /// from "we hit the watchdog":
  ///
  /// - [phase] `'openSession'` — `requestOpenSession()` was issued and
  ///   we are waiting on `didOpenSessionWithError`. [percent] is `-1`.
  /// - [phase] `'catalog'` — KVO update on
  ///   `ICCameraDevice.contentCatalogPercentCompleted`. [percent] is
  ///   in `[0, 100]`.
  /// - [phase] `'ready'` — `didOpenSessionWithError(nil)` fired.
  ///   [percent] is `100`.
  /// - [phase] `'timeout'` — the 120 s watchdog fired before ICA
  ///   responded. [percent] is `-1`. An `onSessionEnded(reason:'timeout')`
  ///   follows.
  ///
  /// [elapsedMs] is measured from the start of the pending
  /// `openSession` call on the Swift side.
  void onSessionOpenProgress(String deviceId, String phase, int percent, int elapsedMs);

  static void setUp(IccPtpFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onDeviceAdded$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onDeviceAdded was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final IccCameraInfo? arg_device = (args[0] as IccCameraInfo?);
          assert(arg_device != null,
              'Argument for dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onDeviceAdded was null, expected non-null IccCameraInfo.');
          try {
            api.onDeviceAdded(arg_device!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onDeviceRemoved$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onDeviceRemoved was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_deviceId = (args[0] as String?);
          assert(arg_deviceId != null,
              'Argument for dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onDeviceRemoved was null, expected non-null String.');
          try {
            api.onDeviceRemoved(arg_deviceId!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onPtpEvent$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onPtpEvent was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_eventCode = (args[0] as int?);
          assert(arg_eventCode != null,
              'Argument for dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onPtpEvent was null, expected non-null int.');
          final int? arg_transactionId = (args[1] as int?);
          assert(arg_transactionId != null,
              'Argument for dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onPtpEvent was null, expected non-null int.');
          final List<int>? arg_params = (args[2] as List<Object?>?)?.cast<int>();
          assert(arg_params != null,
              'Argument for dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onPtpEvent was null, expected non-null List<int>.');
          try {
            api.onPtpEvent(arg_eventCode!, arg_transactionId!, arg_params!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onSessionEnded$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onSessionEnded was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_deviceId = (args[0] as String?);
          assert(arg_deviceId != null,
              'Argument for dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onSessionEnded was null, expected non-null String.');
          final String? arg_reason = (args[1] as String?);
          assert(arg_reason != null,
              'Argument for dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onSessionEnded was null, expected non-null String.');
          try {
            api.onSessionEnded(arg_deviceId!, arg_reason!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onSessionOpenProgress$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onSessionOpenProgress was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_deviceId = (args[0] as String?);
          assert(arg_deviceId != null,
              'Argument for dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onSessionOpenProgress was null, expected non-null String.');
          final String? arg_phase = (args[1] as String?);
          assert(arg_phase != null,
              'Argument for dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onSessionOpenProgress was null, expected non-null String.');
          final int? arg_percent = (args[2] as int?);
          assert(arg_percent != null,
              'Argument for dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onSessionOpenProgress was null, expected non-null int.');
          final int? arg_elapsedMs = (args[3] as int?);
          assert(arg_elapsedMs != null,
              'Argument for dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onSessionOpenProgress was null, expected non-null int.');
          try {
            api.onSessionOpenProgress(arg_deviceId!, arg_phase!, arg_percent!, arg_elapsedMs!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
