// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct IccCameraInfo {
  /// Stable identifier — `ICDevice.persistentIDString` when available,
  /// otherwise `ICDevice.uuidString`.
  var deviceId: String
  /// User-visible product name (`ICDevice.name`).
  var name: String
  /// `'usb'` for USB-C wired cameras, `'network'` for shared cameras
  /// (rare on iPhone), `'unknown'` when ICA can't tell.
  var transportKind: String
  var model: String? = nil
  var serialNumber: String? = nil
  var isRemote: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> IccCameraInfo? {
    let deviceId = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String
    let transportKind = pigeonVar_list[2] as! String
    let model: String? = nilOrValue(pigeonVar_list[3])
    let serialNumber: String? = nilOrValue(pigeonVar_list[4])
    let isRemote = pigeonVar_list[5] as! Bool

    return IccCameraInfo(
      deviceId: deviceId,
      name: name,
      transportKind: transportKind,
      model: model,
      serialNumber: serialNumber,
      isRemote: isRemote
    )
  }
  func toList() -> [Any?] {
    return [
      deviceId,
      name,
      transportKind,
      model,
      serialNumber,
      isRemote,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PtpCommandResult {
  /// PTP response code (e.g. 0x2001 = OK).
  var responseCode: Int64
  /// Response parameters (0..5 uint32 values).
  var responseParams: [Int64]
  /// Data-in payload, if the transaction had a data-IN phase.
  var data: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PtpCommandResult? {
    let responseCode = pigeonVar_list[0] as! Int64
    let responseParams = pigeonVar_list[1] as! [Int64]
    let data: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[2])

    return PtpCommandResult(
      responseCode: responseCode,
      responseParams: responseParams,
      data: data
    )
  }
  func toList() -> [Any?] {
    return [
      responseCode,
      responseParams,
      data,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PtpCommand {
  /// PTP opcode (e.g. 0x1001 = GetDeviceInfo).
  var opcode: Int64
  /// PTP transaction id; caller-managed.
  var transactionId: Int64
  /// Command parameters (0..5 uint32 values).
  var params: [Int64]
  /// Data-OUT payload for dataOut transactions, else null.
  var outData: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PtpCommand? {
    let opcode = pigeonVar_list[0] as! Int64
    let transactionId = pigeonVar_list[1] as! Int64
    let params = pigeonVar_list[2] as! [Int64]
    let outData: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[3])

    return PtpCommand(
      opcode: opcode,
      transactionId: transactionId,
      params: params,
      outData: outData
    )
  }
  func toList() -> [Any?] {
    return [
      opcode,
      transactionId,
      params,
      outData,
    ]
  }
}

private class IccPtpMessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return IccCameraInfo.fromList(self.readValue() as! [Any?])
    case 130:
      return PtpCommandResult.fromList(self.readValue() as! [Any?])
    case 131:
      return PtpCommand.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class IccPtpMessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? IccCameraInfo {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? PtpCommandResult {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? PtpCommand {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class IccPtpMessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return IccPtpMessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return IccPtpMessagesPigeonCodecWriter(data: data)
  }
}

class IccPtpMessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = IccPtpMessagesPigeonCodec(readerWriter: IccPtpMessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol IccPtpHostApi {
  /// Snapshot of currently-visible ICA camera devices.
  func devices() throws -> [IccCameraInfo]
  /// Open an ICA session on the given device. Idempotent — if a session is
  /// already open on the device, returns true immediately.
  func openSession(deviceId: String, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Send a single PTP command over the currently-open session.
  ///
  /// The native side is responsible for building the PTP command block that
  /// `ICCameraDevice.requestSendPTPCommand(_:outData:sendCommandDelegate:...)`
  /// expects. OpenSession / CloseSession opcodes are intercepted natively —
  /// they never reach ICA (the ICA session lifecycle is managed by
  /// [openSession] / [closeSession] above).
  func sendCommand(command: PtpCommand, completion: @escaping (Result<PtpCommandResult, Error>) -> Void)
  /// Close the ICA session on the currently-open device. No-op if none open.
  func closeSession(completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class IccPtpHostApiSetup {
  static var codec: FlutterStandardMessageCodec { IccPtpMessagesPigeonCodec.shared }
  /// Sets up an instance of `IccPtpHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: IccPtpHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Snapshot of currently-visible ICA camera devices.
    let devicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nikon_ptp_flutter.IccPtpHostApi.devices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      devicesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.devices()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      devicesChannel.setMessageHandler(nil)
    }
    /// Open an ICA session on the given device. Idempotent — if a session is
    /// already open on the device, returns true immediately.
    let openSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nikon_ptp_flutter.IccPtpHostApi.openSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        api.openSession(deviceId: deviceIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openSessionChannel.setMessageHandler(nil)
    }
    /// Send a single PTP command over the currently-open session.
    ///
    /// The native side is responsible for building the PTP command block that
    /// `ICCameraDevice.requestSendPTPCommand(_:outData:sendCommandDelegate:...)`
    /// expects. OpenSession / CloseSession opcodes are intercepted natively —
    /// they never reach ICA (the ICA session lifecycle is managed by
    /// [openSession] / [closeSession] above).
    let sendCommandChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nikon_ptp_flutter.IccPtpHostApi.sendCommand\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendCommandChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let commandArg = args[0] as! PtpCommand
        api.sendCommand(command: commandArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendCommandChannel.setMessageHandler(nil)
    }
    /// Close the ICA session on the currently-open device. No-op if none open.
    let closeSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nikon_ptp_flutter.IccPtpHostApi.closeSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeSessionChannel.setMessageHandler { _, reply in
        api.closeSession { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      closeSessionChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol IccPtpFlutterApiProtocol {
  /// A new device appeared in the browser.
  func onDeviceAdded(device deviceArg: IccCameraInfo, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// A device disappeared (unplug / turned off).
  func onDeviceRemoved(deviceId deviceIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Push-based PTP event from `ICCameraDeviceDelegate.didReceivePTPEvent:`.
  /// [transactionId] is the container's transaction id (usually 0 for
  /// asynchronous events unrelated to a specific request).
  func onPtpEvent(eventCode eventCodeArg: Int64, transactionId transactionIdArg: Int64, params paramsArg: [Int64], completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// The active session ended for a reason other than an explicit close —
  /// device unplugged, camera powered off, or an internal ICA error.
  ///
  /// [reason] is one of: `'unplug'`, `'error'`, `'authRevoked'`, `'timeout'`.
  func onSessionEnded(deviceId deviceIdArg: String, reason reasonArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Progress heartbeat during a pending [openSession] call.
  ///
  /// The Swift coordinator emits these at key transitions so the UI can
  /// tell "still waiting on Apple" from "media catalog is 40 % scanned"
  /// from "we hit the watchdog":
  ///
  /// - [phase] `'openSession'` — `requestOpenSession()` was issued and
  ///   we are waiting on `didOpenSessionWithError`. [percent] is `-1`.
  /// - [phase] `'catalog'` — KVO update on
  ///   `ICCameraDevice.contentCatalogPercentCompleted`. [percent] is
  ///   in `[0, 100]`.
  /// - [phase] `'ready'` — `didOpenSessionWithError(nil)` fired.
  ///   [percent] is `100`.
  /// - [phase] `'timeout'` — the 120 s watchdog fired before ICA
  ///   responded. [percent] is `-1`. An `onSessionEnded(reason:'timeout')`
  ///   follows.
  ///
  /// [elapsedMs] is measured from the start of the pending
  /// `openSession` call on the Swift side.
  func onSessionOpenProgress(deviceId deviceIdArg: String, phase phaseArg: String, percent percentArg: Int64, elapsedMs elapsedMsArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Structured diagnostic log line from the Swift coordinator, mirrored
  /// alongside `os.Logger`. Consumed by the in-app "copy logs" panel so
  /// users without a Mac (i.e. anyone running the shipped IPA who does
  /// not own macOS Console.app) can still hand us the Swift-side trace.
  ///
  /// [tag] is a short kebab-case slug like `browser.didAdd`,
  /// `openSession.requestOpenSession`, `catalog.progress`,
  /// `command.request`. [message] is the same string that landed in
  /// `os_log`. [elapsedMs] is `-1` when the event is not tied to a
  /// pending open (e.g. plain browser churn).
  func onDiagnosticLog(tag tagArg: String, message messageArg: String, elapsedMs elapsedMsArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class IccPtpFlutterApi: IccPtpFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: IccPtpMessagesPigeonCodec {
    return IccPtpMessagesPigeonCodec.shared
  }
  /// A new device appeared in the browser.
  func onDeviceAdded(device deviceArg: IccCameraInfo, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onDeviceAdded\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// A device disappeared (unplug / turned off).
  func onDeviceRemoved(deviceId deviceIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onDeviceRemoved\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Push-based PTP event from `ICCameraDeviceDelegate.didReceivePTPEvent:`.
  /// [transactionId] is the container's transaction id (usually 0 for
  /// asynchronous events unrelated to a specific request).
  func onPtpEvent(eventCode eventCodeArg: Int64, transactionId transactionIdArg: Int64, params paramsArg: [Int64], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onPtpEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventCodeArg, transactionIdArg, paramsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// The active session ended for a reason other than an explicit close —
  /// device unplugged, camera powered off, or an internal ICA error.
  ///
  /// [reason] is one of: `'unplug'`, `'error'`, `'authRevoked'`, `'timeout'`.
  func onSessionEnded(deviceId deviceIdArg: String, reason reasonArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onSessionEnded\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceIdArg, reasonArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Progress heartbeat during a pending [openSession] call.
  ///
  /// The Swift coordinator emits these at key transitions so the UI can
  /// tell "still waiting on Apple" from "media catalog is 40 % scanned"
  /// from "we hit the watchdog":
  ///
  /// - [phase] `'openSession'` — `requestOpenSession()` was issued and
  ///   we are waiting on `didOpenSessionWithError`. [percent] is `-1`.
  /// - [phase] `'catalog'` — KVO update on
  ///   `ICCameraDevice.contentCatalogPercentCompleted`. [percent] is
  ///   in `[0, 100]`.
  /// - [phase] `'ready'` — `didOpenSessionWithError(nil)` fired.
  ///   [percent] is `100`.
  /// - [phase] `'timeout'` — the 120 s watchdog fired before ICA
  ///   responded. [percent] is `-1`. An `onSessionEnded(reason:'timeout')`
  ///   follows.
  ///
  /// [elapsedMs] is measured from the start of the pending
  /// `openSession` call on the Swift side.
  func onSessionOpenProgress(deviceId deviceIdArg: String, phase phaseArg: String, percent percentArg: Int64, elapsedMs elapsedMsArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onSessionOpenProgress\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceIdArg, phaseArg, percentArg, elapsedMsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Structured diagnostic log line from the Swift coordinator, mirrored
  /// alongside `os.Logger`. Consumed by the in-app "copy logs" panel so
  /// users without a Mac (i.e. anyone running the shipped IPA who does
  /// not own macOS Console.app) can still hand us the Swift-side trace.
  ///
  /// [tag] is a short kebab-case slug like `browser.didAdd`,
  /// `openSession.requestOpenSession`, `catalog.progress`,
  /// `command.request`. [message] is the same string that landed in
  /// `os_log`. [elapsedMs] is `-1` when the event is not tied to a
  /// pending open (e.g. plain browser churn).
  func onDiagnosticLog(tag tagArg: String, message messageArg: String, elapsedMs elapsedMsArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.nikon_ptp_flutter.IccPtpFlutterApi.onDiagnosticLog\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([tagArg, messageArg, elapsedMsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
